### ISSUE TITLE
Publish to Docker Hub

### ISSUE THREAD

**Issue by vlsi** [SeemsFishy/sing-box-routeros#2]
WDYT of publishing the images to Docker Hub?

**Comment by SeemsFishy** [comment]
It's not hard to do, but what's the point?

**Comment by vlsi** [comment]
The download from ghcr.io requires a token while the download from DockerHub does not need a token, so it is easier

**Comment by SeemsFishy** [comment]
I'm not sure what are you talking about. Downloading packages from public github repos should not require any specific access tokens. Am I missing something?

**Comment by vlsi** [comment]
Yeah, download from ghcr.io works without tokens indeed
